name: Continuous Integration

on:
  push:
  pull_request:

jobs:
  stylua:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run StyLua
        uses: JohnnyMorganz/stylua-action@1.0.0
